SRCS += 
SRCS += Sources/box/ps_free_box.c
SRCS += Sources/box/ps_box_create.c
SRCS += Sources/box/ps_box_init.c
SRCS += Sources/memory/ps_final_free.c
SRCS += Sources/utils/ps_atoi.c
SRCS += Sources/utils/ps_free_string_array.c
SRCS += Sources/main.c
SRCS += Sources/errors/ps_errors.c
SRCS += Sources/parsing/ps_parsing.c
